const {ShardingManager} = require("discord.js")
const fs = require('fs')
const conf = require(`./config.json`)
const mngr = new ShardingManager(`./solace.js`, {token: conf.token, respawn: true, totalShards: 1})
eval(fs.readFileSync(`./register.js`, 'utf-8'))
mngr.spawn()