const {ShardingManager} = require("discord.js")
const fs = require('fs')
const conf = require(`./configuration.json`)
const path = require('path')
const mngr = new ShardingManager(`./solace.js`, {token: conf.token, respawn: true, totalShards: 1})
eval(fs.readFileSync(`./startup/register.js`, 'utf-8'))
eval(fs.readFileSync(`./startup/commands.js`, 'utf-8'))
mngr.spawn()